import type { Metadata } from "next";
import { Atma } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/shared/helpers/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const indieFlower = Atma({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(indieFlower.className, "antialiased text-brown-dark bg-brown-light ")}>
        {children}
      </body>
    </html>
  );
}
